package caches.hardware.ocp

import chisel3._

// Constants for MCmd
object OcpCmd {
  val IDLE = "b000".U(3.W)
  val WR = "b001".U(3.W)
  val RD = "b010".U(3.W)
}

// Constants for SResp
object OcpResp {
  val NULL = "b00".U(2.W)
  val DVA = "b01".U(2.W)
  val FAIL = "b10".U(2.W)
  val ERR = "b11".U(2.W)
}

// Signals generated by master
class OcpMasterSignals(val addrWidth: Int, val dataWidth: Int) extends Bundle() {
  val Cmd = Output(UInt(3.W))
  val Addr = Output(UInt(addrWidth.W))
  val Data = Output(UInt(dataWidth.W))
}

// Signals generated by slave
class OcpSlaveSignals(val dataWidth: Int) extends Bundle() {
  val Resp = Input(UInt(2.W))
  val Data = Input(UInt(dataWidth.W))
}
