name: Sbt Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # Setup verilator so that chisel tests can use it as a backend
      - name: Setup verilator
        uses: v0xnihili/install-verilator-action@main
        with:
          version: "v4.100" # One of the few verilator versions that are compatible with latest ubuntu release and chisel test

        # Check if the verilator can be found
      - name: Validate verilator
        run: verilator --version

      - name: Setup Scala
        uses: olafurpg/setup-scala@v14

      - name: Run sbt tests
        run: sbt test
